### ISSUE TITLE
TestWithRoundRobin flaky

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#1117]
This is an actual bug, not the `glide update` issue I had: https://travis-ci.org/yarpc/yarpc-go/jobs/243674162#L576

**Comment by peter-edge** [comment]
![image](https://user-images.githubusercontent.com/4228796/27300893-93dbb4da-5531-11e7-9b5c-c80ddd714a09.png)

**Comment by kriskowal** [comment]
This should be addressed by #1130

**Comment by peter-edge** [comment]
This happened again today, after merging the timeout stuff. I think this tests needs to be skipped until it can be fixed.

**Comment by peter-edge** [comment]
This is still happening @kriskowal 

--- FAIL: TestWithRoundRobin (0.19s)
	Error Trace:	util.go:214
			peer_test.go:112
	Error:      	Received unexpected error:
	            	dial tcp 172.17.0.7:42855: getsockopt: connection refused
	Error Trace:	util.go:214
			peer_test.go:112
	Error:      	Received unexpected error:
	            	dial tcp 172.17.0.7:42855: getsockopt: connection refused
FAIL
coverage: 49.7% of statements in go.uber.org/yarpc, go.uber.org/yarpc/api/backoff, go.uber.org/yarpc/api/encoding, go.uber.org/yarpc/api/middleware, go.uber.org/yarpc/api/peer, go.uber.org/yarpc/api/transport, go.uber.org/yarpc/api/transport/transporttest, go.uber.org/yarpc/api/yarpcerrors, go.uber.org/yarpc/encoding/json, go.uber.org/yarpc/encoding/raw, go.uber.org/yarpc/internal, go.uber.org/yarpc/internal/backoff, go.uber.org/yarpc/internal/clientconfig, go.uber.org/yarpc/internal/encoding, go.uber.org/yarpc/internal/errors, go.uber.org/yarpc/internal/humanize, go.uber.org/yarpc/internal/inboundmiddleware, go.uber.org/yarpc/internal/integrationtest, go.uber.org/yarpc/internal/interpolate, go.uber.org/yarpc/internal/introspection, go.uber.org/yarpc/internal/iopool, go.uber.org/yarpc/internal/observability, go.uber.org/yarpc/internal/outboundmiddleware, go.uber.org/yarpc/internal/pally, go.uber.org/yarpc/internal/request, go.uber.org/yarpc/internal/routertest, go.uber.org/yarpc/internal/sync, go.uber.org/yarpc/internal/testtime, go.uber.org/yarpc/peer, go.uber.org/yarpc/peer/hostport, go.uber.org/yarpc/transport/tchannel, go.uber.org/yarpc/transport/tchannel/internal, go.uber.org/yarpc/x/config
FAIL	go.uber.org/yarpc/transport/tchannel	10.192s
